#!/usr/bin/python

import sys
import csv

def get_cols(line):
	return [ line.find(name) for name in line.split() ]

def bom_split(line, cols):
	cols2 = cols + [None]
	return [ line[cols2[i]:cols2[i+1]].strip() for i in xrange(len(cols)) ]

f = iter(sys.stdin)

h1 = f.next()
h2 = f.next()
h3 = f.next()

cols = get_cols(h3) 

rows = [ bom_split(line, cols) for line in f ]

rows.sort(key=lambda x:x[1:])

w = csv.writer(sys.stdout, dialect=csv.excel)
w.writerow(bom_split(h3, cols) + ['Qty'])

new_row = []
for row in rows:
	if not new_row or (row[1:] != new_row[1:-1]):
		if new_row:
			w.writerow(new_row)
		new_row = list(row) + [1]
	else:
		new_row[0] = new_row[0] + ', ' + row[0]
		new_row[-1] += 1

w.writerow(new_row)
