#!/usr/bin/python

import os
from eagle_automation.config import *
from eagle_automation.export import	EaglePNGExport, \
					EaglePDFExport, \
					EagleGerberExport, \
					EagleExcellonExport
import sys

out_types = {	'png': EaglePNGExport,
		'pdf': EaglePDFExport,
		'gerber': EagleGerberExport,
		'excellon': EagleExcellonExport }

def usage():
	print """eagleexport, export layers from CadSoft Eagle files
Copyright (C) 2012  Tomaz Solc <tomaz.solc@tablix.org>

USAGE: eagleexport input-file type output-file:layer ...

type can be any of %s

layer can be any of %s""" % (
		', '.join(out_types.iterkeys()),
		', '.join(LAYERS.iterkeys()) )

	sys.exit(1)

def main():
	if len(sys.argv) < 4:
		usage()

	in_path, out_type = sys.argv[1:3]

	layers = []
	out_paths = []
	for arg in sys.argv[3:]:
		try:
			out_path, layer_name = arg.split(":")
		except ValueError:
			print "Missing :"
			sys.exit(1)

		try:
			layer = LAYERS[layer_name]
		except KeyError:
			print "Unknown layer: " + layer_name
			sys.exit(1)

		layers.append(layer)
		out_paths.append(out_path)

	try:
		export_class = out_types[out_type]
	except KeyError:
		print "Unknown type: " + out_type
		sys.exit(1)

	export_class().export(in_path, layers, out_paths)

main()
