#!/usr/bin/python

import os
import subprocess
import sys
import tempfile
from PIL import Image, ImageOps, ImageChops 

EAGLE = "/home/avian/local/eagle-5.11.0/bin/eagle"
DPI = 300

def to_png(path):

	ext = path.split('.')[-1]

	layers_cfg = {	'brd': [
				"tPlace tNames tDocu",
				"tCream",
				"tStop",
				"Top Pads Vias",
				"Bottom Pads Vias",
				"bStop",
				"bCream",
				"bPlace bNames bDocu",
			],
			'sch': [
				"ALL",
			],
		}

	layers = layers_cfg[ext]

	workdir = tempfile.mkdtemp()
	#workdir = "/tmp/a"

	scrpath = os.path.join(workdir, "export.scr")
	scr = open(scrpath, "w")

	scr.write("%s:\nDISPLAY ALL\n" % (ext.upper()))

	if ext == "brd":
		scr.write("RATSNEST\n")

	pngs = []

	for layer in layers:
		png = "".join(layer.split()).lower() + ".png"
		png = os.path.join(workdir, png)
		pngs.append(png)

		scr.write("DISPLAY None\nDISPLAY %s\n" % (layer,))
		scr.write("EXPORT IMAGE %s MONOCHROME %d\n" % (png, DPI))

	scr.write("QUIT\n")
	scr.close()

	cmd = [EAGLE, "-S" + scrpath, path]
	subprocess.call(cmd)

	os.unlink(scrpath)

	oim = None
	for i, png in enumerate(pngs):
		im = Image.open(png).convert("L")
		if oim is None:
			oim = im
		else:
			oim = Image.blend(oim, im, 1.0/(1.0+i))

		os.unlink(png)

	os.rmdir(workdir)

	return oim

def main():
	try:
		a_im = to_png(sys.argv[1])
		b_im = to_png(sys.argv[2])
	except KeyError:
		return

	added = ImageOps.autocontrast(ImageChops.subtract(b_im, a_im), 0)
	deled = ImageOps.autocontrast(ImageChops.subtract(a_im, b_im), 0)
	same = Image.blend(a_im, b_im, 0.5)

	deled = ImageOps.colorize(deled, "#000", "#f00")
	added = ImageOps.colorize(added, "#000", "#00f")
	same = ImageOps.colorize(same, "#000", "#777")

	im = ImageChops.add(ImageChops.add(added, deled), same)

	im.show()

main()
